DROP DATABASE IF EXISTS `TRIPSCATALOG`;
CREATE DATABASE `TRIPSCATALOG`;
USE `TRIPSCATALOG`;

CREATE TABLE `USER` (
	`ID` INT NOT NULL AUTO_INCREMENT,
    `FIRST_NAME` VARCHAR(255) NOT NULL,
    `LAST_NAME` VARCHAR(255) NOT NULL,
    `USER_NAME` VARCHAR(255) NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `CITY` VARCHAR(255) NOT NULL,
    `ADDRESS` VARCHAR(1000) NOT NULL,
    `PHONE` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `TRIP` (
	`USER_ID` INT NOT NULL,
    `ID` INT NOT NULL AUTO_INCREMENT,
    `TRIP_NAME` VARCHAR(255),
    `DATE_FROM` DATE,
    `DATE_TO` DATE,
    `TRIP_IMPRESSIONS` VARCHAR(2000),
    `PHOTO1_PATH` VARCHAR(1000),
    `PHOTO1_IMPRESSIONS` VARCHAR(2000),
	`PHOTO2_PATH` VARCHAR(1000),
    `PHOTO2_IMPRESSIONS` VARCHAR(2000),
    `LOCATION` VARCHAR(2000),
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`ID`)
);

SELECT * FROM `USER`;
SELECT * FROM `TRIP`;